# Site settings
title: William
description: William is a minimal yet powerful Jekyll theme for your blogs and websites.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
# baseurl: "/canidy.github.io/" # the subpath of your site, e.g. /blog/ or / for root
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://canidy.github.io/" # the protocal & base hostname for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: bill
twitter: bill
github:  canidy

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: canidy #github username
repo: canidy.github.io #github repository
branch: master #branch
relative_source: ./ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://canidy.github.io/
source_url:  https://github.com/canidy/canidy.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
theme: minima